### ISSUE TITLE
It was not possible to connect to the redis server(s)

### ISSUE THREAD

**Issue by kumarmo2** [StackExchange/StackExchange.Redis#1851]
I am running 2 redis instances using docker exposed via ports 8000 and 8001. I am using envoy to act as a redis proxy.

Here is my envoy config

```
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9001

static_resources:
  listeners:
  - name: redis-proxy-listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 7000
    stat_prefix: redis-proxy-listener
    filter_chains:
      - filters:
          - name: envoy.filters.network.redis_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
              stat_prefix: redis-proxy-filter
              settings:
                op_timeout: 10s
              prefix_routes:
                catch_all_route:
                    cluster: redis-cluster


  clusters:
  - name: redis-cluster
    connect_timeout: 20s
    type: static
    lb_policy: RING_HASH
    load_assignment:
      cluster_name: redis-cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8000
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8001

```

As it can be seen in the config above, the proxy listens on port `7000`. 

If i connect using `redis-cli` via command `redis-cli -p 7000`. It gets connected. 

But if i try to connect using `SE-Redis` on `localhost:7000`. I get this error. 

```
"It was not possible to connect to the redis server(s). ProtocolFailure (None, last-recv: 236) on 127.0.0.1:7000/Interactive, 
Flushed/ComputeResult, last: ECHO, origin: SetResult, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state:
ConnectedEstablishing, mgr: 8 of 10 available, last-heartbeat: never, global: 5s ago, v: 2.2.4.27433"
```
Now in the message its showing `last: ECHO`. So I am guessing the client issued the `ECHO` command. 

I know the `envoy` currently don't support the command. 

Is there any way I can make the client work while using envoy as a redis proxy ?
