### ISSUE TITLE
Publish/Subscribe on a gitlab ci service

### ISSUE THREAD

**Issue by trampster** [StackExchange/StackExchange.Redis#2262]
We are using a gitlab ci service to run redis for the purpose of running integration tests.

```
services:
        - name: $MIRRORED_IMAGE_PREFIX/redis:7-alpine3.16
          alias: redis
          command: [ "redis-server", "--save", "", "--databases", "1" ]
```

We publish a simple message
```
var subscriber = _redisMultiplexer.GetSubscriber();
await subscriber.PublishAsync("document_event", documentType);
```

 And subscribe to it (from the same multiplexer)
```
var subscriber = _redisMultiplexer.GetSubscriber();
var channel = await subscriber.SubscribeAsync($"document_event");
while (true)
{
     var channelMessage = await channel.ReadAsync(cancellationToken);
     //handling code here
}
```

This works locally using docker compose, but on the gitlab ci we never receive the message. We can talk to redis fine for getting and setting values, but we never receive any message.

We are wondering if there are any known issues around this. Does the pub/sub use a different port to other redis operations? What could cause pub/sub to not work but normal redis operations to work correctly?

NOTE: we are aware that subscribe should be on it's own connection, but assume that calling GetSubscriber from the multiplexer would handle giving us our own connection. In addition this works when using docker-compose locally.
